// AUTOGENERATED by amboras-dev-orchestrator (Phase C — multi-theme A/B).
// CONTRACT v14
// Do NOT edit by hand. Source of truth:
//   backend/src/modules/plugins/templates/middleware-template.ts
//
// This file is shipped to every storefront unconditionally. The
// AB_ENABLED env-var check on the first line of middleware() short-circuits
// flag-off stores at zero cost beyond one boolean read per request.
//
// Cookies set here (amb_vid, amb_fp, amb_theme) are strictly-necessary
// under GDPR/ePrivacy: they exist solely to deliver the variant the buyer
// has been assigned to — no profiling, no cross-site tracking. They are
// intentionally NOT routed through lib/cookie-consent.ts (review item L6).
//
// amboras_consent (geo auto-consent, CONTRACT v6) is different: it IS the
// consent record owned client-side by lib/cookie-consent.ts. The middleware
// writes it — analytics:true — ONLY for visitors outside the ePrivacy
// opt-in jurisdictions (EEA + UK + CH) and ONLY when no decision cookie
// exists yet, so relaxed-cookie-law traffic gets analytics from the first
// page view without a banner. Opt-in-country and unknown-geo visitors are
// never auto-granted (banner shows as before); an explicit Decline is
// never overridden.
//
// frame-ancestors (CONTRACT v9) is the storefront's only defense against
// being embedded by a site that isn't ours. See the FRAME_ANCESTORS block
// below for why it lives at the edge and not in the storefront app.

import { NextRequest, NextResponse } from 'next/server'

const AB_ENABLED = process.env.AB_ENABLED === 'true'
const ROUTER_URL = process.env.VARIANT_ROUTER_URL
const ROUTER_SECRET = process.env.VARIANT_ROUTER_SECRET
// orchestrator stores.id (uuid). NOT the same as NEXT_PUBLIC_STORE_ID, which
// is the dev-env uuid used as the Medusa tenant key. The variant-router keys
// snapshots by stores.id — passing the Medusa tenant key here returns
// reason=no_group for every resolve and the AB never fires. See template
// header comment for the full why.
const STORE_ID = process.env.NEXT_PUBLIC_AB_STORE_ID
// Staging-only escape hatch: when 'true', `?_v=<slug>` is honored without
// the admin-cookie check. Wired here as a deferred mechanism for
// review item C3 (full admin-JWT verification ships when the orchestrator
// learns to mint `amb_admin` from the dashboard "Preview" action).
const PREVIEW_OVERRIDE_ENABLED = process.env.PREVIEW_OVERRIDE_ENABLED === 'true'

// ── Draft password gate (CONTRACT v7) ──────────────────────────────────────
// Baked PER-DEPLOYMENT (not per-project) only into a store's DRAFT staging
// build by DraftDeployService, so ONLY the draft is gated — live + A/B variant
// deployments carry none of these and the gate is inert there (short-circuit
// below). DRAFT_PASSWORD_HASH is the SAME pbkdf2$iter$salt$hash the
// orchestrator produces (common/utils/draft-password.util.ts); Web-Crypto
// PBKDF2-SHA256 re-derives it byte-for-byte. Never NEXT_PUBLIC_ (secret stays
// server/edge-side, never shipped to the browser).
const DRAFT_PASSWORD_ENABLED = process.env.DRAFT_PASSWORD_ENABLED === 'true'
const DRAFT_PASSWORD_HASH = process.env.DRAFT_PASSWORD_HASH
const DRAFT_GATE_SECRET = process.env.DRAFT_GATE_SECRET
const DRAFT_UNLOCK_COOKIE = 'amboras_draft_unlock'
const DRAFT_UNLOCK_QUERY = '__amboras_unlock'
// ADMIN skip-prompt token param. The orchestrator mints a short-lived signed
// token (same <exp>.<sig> shape as the unlock cookie) for the owner; when it is
// valid the edge auto-unlocks WITHOUT the password prompt. The token carries NO
// password. MUST match the orchestrator's DraftPreviewSettingsService.mintOpenUrl.
const DRAFT_ADMIN_QUERY = '__amboras_admin'
// MUST match the admin's use-draft-preview-embed hook.
const DRAFT_EMBED_QUERY = '__amboras_embed'
// Fallback for browsers with no Sec-Fetch-Dest: for its 8h TTL every page
// on this draft is served bannerless, top-level opens included.
const DRAFT_EMBED_COOKIE = 'amboras_draft_embed'
const DRAFT_COOKIE_TTL_S = 8 * 60 * 60 // 8h
// Human label for the draft banner (the theme/draft name). Baked per-deploy by
// DraftDeployService alongside the password env; safe to ship to the browser
// (it's the merchant's own draft name), so it renders in the injected banner.
const DRAFT_NAME = process.env.DRAFT_NAME || 'Draft'
// Header that marks the middleware's OWN inner fetch when it re-requests the
// page to inject the banner — its presence short-circuits a second injection,
// so the sub-fetch can never recurse.
const DRAFT_BANNER_INNER_HEADER = 'x-amboras-draft-inner'
// Admin origins the draft page may postMessage to. Keep in sync with FRAME_ANCESTORS_CSP.
const ADMIN_ORIGINS_JS =
  'var OK=["https://admin.amboras.com","https://staging-admin.amboras.com","http://localhost:3001"];'
// Amboras mark — shared by the password gate page and the DRAFT banner so the
// two surfaces cannot drift. width/height 100% so it fills whatever box it sits
// in (a 44px logo on the gate card, a small tile in the banner).
const AMBORAS_LOGO_SVG =
  '<svg width="100%" height="100%" viewBox="0 0 463 426" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path fill-rule="evenodd" clip-rule="evenodd" d="M193.122 18.4818C206.004 -5.71854 240.49 -6.26753 254.137 17.5104L458.296 373.24C472.974 398.818 451.243 429.934 422.175 424.96L266.283 398.281C239.111 393.631 211.338 393.732 184.202 398.58L41.0757 424.15C12.4373 429.266 -9.50096 399.127 4.16867 373.446L193.122 18.4818ZM253.591 105.444C239.939 83.8945 208.525 83.8208 194.773 105.307L188.313 115.402L141.329 202.49L90.4362 307.403C78.6492 331.701 97.7709 359.596 124.685 357.365L222.22 349.278L341.624 340.087C367.835 338.07 382.468 308.874 368.4 286.667L253.591 105.444Z" fill="#faf6f2"/><path d="M319.895 269.476C332.863 293.045 315.385 321.798 288.492 321.137L162.309 318.037C135.508 317.378 119.447 287.981 133.372 265.072L198.71 157.585C212.635 134.677 246.126 135.4 259.049 158.888L319.895 269.476Z" fill="#faf6f2"/></svg>'

// ── Frame-embedding policy (CONTRACT v9) ───────────────────────────────────
// Two admin-preview integrations inside the storefront app decide they are
// talking to the dashboard on the strength of one test — `window.parent !==
// window` — and nothing else: the rrweb recording shim in app/layout.tsx and
// components/element-picker-listener.tsx. Being framed is not an identity.
// Any site can put a public storefront in an iframe, and both integrations
// would then stream page content, route changes and typed input to whatever
// page holds that frame.
//
// Neither can be fixed from the orchestrator: they live in the merchant's own
// repo, forked from the starter template at store creation, so a template fix
// reaches no existing store. This header is what makes them unreachable —
// the browser refuses the frame before either can start.
//
// The list is every origin WE embed a storefront from: the Online Store
// preview tab (proxy AND direct layers), the dashboard home tiles
// (home-variants.tsx frames the store's LIVE url), and the internal admin
// panel. Dropping an entry does not break a storefront — it silently blanks
// one of those panes, which no build or test here would catch.
//
// Deliberately a baked constant, not a process.env read: the emitted file
// stays byte-identical across environments, so the infra heal has no drift to
// chase and no Vercel env var has to be backfilled across the fleet. The
// extra entries cost nothing — they are our own admin origins. The value is
// substituted at build time from FRAME_ANCESTORS_CSP in this module, which
// PreviewProxyService serves too, so the two surfaces cannot disagree.
const FRAME_ANCESTORS_CSP = "frame-ancestors 'self' https://admin.amboras.com https://staging-admin.amboras.com http://localhost:3001"

// ── Accept Hosted relay exception (CONTRACT v13) ───────────────────────────
// The authorize-net plugin's embedded card form is served by Authorize.Net,
// which loads the relay page below in a hidden iframe INSIDE that form. The
// relay hands the form's messages (resizeWindow / cancel / transactResponse)
// to this page by direct JS property access —
// `window.parent.parent.AmborasAuthorizeNet` — which only works SAME-ORIGIN.
// So the relay cannot be moved to another host to dodge this header: it has
// to sit on the storefront, and Authorize.Net has to be allowed to frame it.
//
// Hence the exception is scoped to that ONE path instead of widening the list
// above. The relay is a blank page carrying a single postMessage listener —
// no content, no controls, no data — so framing it exposes nothing, while
// every real page (checkout above all) keeps the unmodified policy. Stores
// without the plugin simply never serve this path.
//
// frame-ancestors is matched against EVERY ancestor in the chain, not just
// the immediate parent, and that chain is
// storefront checkout -> Accept Hosted form -> relay. `'self'` is therefore
// load-bearing here too: dropping it breaks the relay as surely as omitting
// the Authorize.Net origins.
const PAYMENT_RELAY_PATH = "/authorize-net-communicator.html"
const RELAY_FRAME_ANCESTORS_CSP = "frame-ancestors 'self' https://admin.amboras.com https://staging-admin.amboras.com http://localhost:3001 https://accept.authorize.net https://test.authorize.net"

export const config = {
  matcher: [
    // Match every path except framework internals, the public API surface,
    // and obvious static assets — but DO include the JS chunk + CSS asset
    // paths so middleware can rewrite them to the variant deploy on AB
    // stores (post-2026-05-30 middleware-proxy architecture). Fonts /
    // images / media are still excluded to keep middleware invocation
    // volume bounded (review item perf-2: ~30 chunks/css per page load is
    // OK; ~hundreds of font/image requests is not).
    // Webpack layout.
    '/_next/static/chunks/:path*',
    '/_next/static/css/:path*',
    // TURBOPACK layout. Turbopack emits every JS chunk AND every CSS file under
    // /_next/static/immutable/chunks/, which none of the patterns above match
    // — and the catch-all below explicitly excludes _next/. So on a Turbopack
    // build the asset branch NEVER ran: the HTML came from the assigned variant
    // deploy while its chunks fell through to the control deploy, whose content
    // hashes differ. Every asset 404'd and the storefront rendered as unstyled
    // text — the exact cross-deploy chunk skew the branch below exists to stop.
    //
    // Invisible to every check we had: HTTP 200 on the HTML, assets fine on the
    // variant's own *.vercel.app (one deploy serves both there, so nothing can
    // skew), and fine for anyone whose browser had the files cached. It only
    // broke first-time visitors on the custom domain, and only while an A/B
    // campaign was assigning them a variant. (deepresetlabs.com, 2026-09-03.)
    '/_next/static/immutable/:path*',
    '/((?!_next/|api/|favicon\\.ico|robots\\.txt|sitemap\\.xml).*)',
  ],
}

const BOT_UA_RE = /bot|crawl|spider|slurp|googlebot|bingbot|baidu|yandex|duckduckbot|facebookexternalhit|twitterbot|linkedinbot/i

// Device classification — MUST mirror the variant-router's targeting.ts so a
// device switch is detected the same way the router applies device targeting
// (tablet before mobile; iPads sometimes carry "Mobile" in the UA). Used only to
// invalidate the cookie fast path when the device changes within the TTL window,
// so device-targeted assignments (and same-browser responsive testing) stay live.
const TABLET_UA_RE = /ipad|tablet|playbook|kindle|silk(?!.*mobile)/i
const MOBILE_UA_RE = /mobi|iphone|ipod|android(?!.*tablet)|blackberry|opera mini|windows phone/i
function classifyDevice(ua: string): 'mobile' | 'tablet' | 'desktop' {
  if (!ua) return 'desktop'
  if (TABLET_UA_RE.test(ua)) return 'tablet'
  if (MOBILE_UA_RE.test(ua)) return 'mobile'
  return 'desktop'
}

const COOKIE_OPTS = {
  sameSite: 'lax' as const,
  secure: true,
  path: '/',
}
const THIRTY_DAYS = 60 * 60 * 24 * 30
const NINETY_DAYS = 60 * 60 * 24 * 90
// How long a signed assignment is trusted before the middleware re-resolves
// through the router. Within this window a returning visitor is served straight
// from the cookie (no router/Redis round-trip), which is the dominant page-view
// cost. Admin changes (targeting/weight/promote/cancel/rebuild) reach an active
// visitor on their next re-resolve, i.e. within this TTL; new visitors and
// anyone past it get them immediately. In milliseconds (compared vs Date.now()).
const RESOLVE_TTL_MS = 5 * 60 * 1000

// ── Geo auto-consent (CONTRACT v6) ──────────────────────────────────────────
// Countries with ePrivacy-style OPT-IN cookie law keep the consent banner;
// everyone else gets analytics consent auto-granted server-side so analytics
// (v2 ingest, PostHog, Meta pixel — all gated on hasAnalyticsConsent()) are
// live from the first page view. List = EU27 + EEA (IS/LI/NO) + UK + CH.
// Unknown/missing country (e.g. local dev, non-Vercel edge) → keep banner.
const CONSENT_OPT_IN_COUNTRIES = new Set([
  'AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT',
  'LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE',
  'IS','LI','NO','GB','CH',
])
// Contract owned by lib/cookie-consent.ts: URL-encoded JSON {analytics, ts},
// absence = undecided (banner shows). Names/values MUST stay in sync with it.
const CONSENT_COOKIE = 'amboras_consent'
const CONSENT_MAX_AGE = 31536000 // 1 year — mirrors client-side CONSENT_MAX_AGE

// Auto-grant analytics consent for visitors outside the opt-in jurisdictions.
// Never overrides an existing decision cookie (an explicit Decline stays).
// The extra `auto: 'geo'` field is additive — hasAnalyticsConsent() only
// checks `analytics === true` — and marks the grant as geo-derived rather
// than an explicit Accept click. NextResponse.cookies.set URL-encodes the
// JSON value, matching the client's decodeURIComponent + JSON.parse.
function applyGeoConsent(req: NextRequest, response: NextResponse): NextResponse {
  if (req.cookies.get(CONSENT_COOKIE)?.value) return response
  const country = (req.headers.get('x-vercel-ip-country') ?? '').toUpperCase()
  if (!country || CONSENT_OPT_IN_COUNTRIES.has(country)) return response
  response.cookies.set(
    CONSENT_COOKIE,
    JSON.stringify({ analytics: true, ts: new Date().toISOString(), auto: 'geo' }),
    { ...COOKIE_OPTS, maxAge: CONSENT_MAX_AGE },
  )
  return response
}

// Stamped on EVERY response this file returns. The bot redirect, the three
// asset-branch returns and the draft gate never pass through applyGeoConsent,
// so this is applied by the exported wrapper instead of at each return site —
// a branch added later cannot ship without it.
//
// An existing frame-ancestors directive (merchant CSP, plugin, hosting layer)
// is left alone. An existing CSP without one gets ours appended: two CSP
// headers intersect, so appending can only ever tighten the policy.
function applyFrameAncestors<T extends Response>(response: T, pathname: string): T {
  try {
    const policy =
      pathname === PAYMENT_RELAY_PATH ? RELAY_FRAME_ANCESTORS_CSP : FRAME_ANCESTORS_CSP
    const existing = response.headers.get('content-security-policy')
    if (!existing) {
      response.headers.set('content-security-policy', policy)
    } else if (!existing.includes('frame-ancestors')) {
      response.headers.append('content-security-policy', policy)
    }
  } catch {
    // Immutable headers on an exotic Response — never break the response
    // over a defense-in-depth header.
  }
  return response
}

// The relay's frame-ancestors is injected HERE, per request — it is not part
// of the static file's bytes. Vercel happily caches the whole response,
// header included, and serves it with `max-age=0, must-revalidate`. That
// combination is a trap: the revalidation 304 carries NO
// content-security-policy, and RFC 9111 §4.3.4 says a 304 updates only the
// headers it actually contains — so a client that cached this page under an
// older policy keeps that policy FOREVER, because the file's bytes (and its
// ETag) never change when we edit the policy.
//
// Observed on staging 2026-09-17: after shipping the Accept Hosted origins,
// browsers that had loaded the relay minutes earlier kept replaying the old
// header (frozen `age`, 304 on revalidate) and embedded checkout stayed
// broken for them while a fresh client worked.
//
// no-store is the fix and costs nothing: the page is ~1.2 KB and loads once
// per checkout. It also means any future change to the relay policy takes
// effect on the next request instead of whenever an ETag happens to move.
function applyRelayCacheControl<T extends Response>(response: T, pathname: string): T {
  if (pathname !== PAYMENT_RELAY_PATH) return response
  try {
    response.headers.set('cache-control', 'no-store')
  } catch {
    // Immutable headers — same posture as above.
  }
  return response
}

interface ResolveResponse {
  themeId: string
  deploymentUrl: string
  isControl: boolean
  fingerprint?: string
  groupVersion: string
  // The active A/B group id (null on control fallbacks). Carried into the
  // amb_theme cookie so the ab-attribution plugin can stamp ab_group_id onto
  // analytics events. Without it every event lands NULL and the A/B rollup
  // (which filters on ab_group_id IS NOT NULL) shows zero.
  abGroupId?: string | null
  assignedAt?: string
  reason?: string
}

interface CookiePayload {
  themeId: string
  groupVersion: string
  // Optional + additive: pre-2026-05-31 cookies omit it. The ab-attribution
  // plugin reads it from the decoded cookie payload; verify() does not require
  // it so old signed cookies remain valid.
  abGroupId?: string | null
  // Epoch ms when this assignment was last resolved through the router. The HTML
  // path trusts the cookie (skips the router) while `Date.now() - resolvedAt <
  // RESOLVE_TTL_MS`. Optional + additive: pre-v4 cookies omit it and are treated
  // as expired (re-resolve once), so the rollout is seamless.
  resolvedAt?: number
  // Device class (classifyDevice) at the time of resolve. The fast path only
  // trusts the cookie while the current request's device matches — a device
  // switch (responsive testing, or device-targeted experiments) re-resolves so
  // device targeting stays live. Optional + additive: pre-v5 cookies omit it and
  // therefore re-resolve once.
  device?: string
  // The variant deploy URL for this assignment, as returned by the router's
  // /v1/resolve (`resolved.deploymentUrl`). Empty/absent ⇒ control.
  //
  // Carried in the cookie ONLY because the asset-proxy branch
  // (/_next/static/*) must rewrite ~30 chunk/CSS requests per page WITHOUT a
  // router round-trip each. It is safe to trust as a rewrite target because
  // the whole payload is HMAC-signed (signCookie/verifyCookie) — a forged URL
  // can't pass verification (this satisfies the original C1 concern, which was
  // about UNSIGNED cookie data dictating the rewrite). The HTML path does NOT
  // read this; it uses the fresh `resolved.deploymentUrl` from its own resolve
  // call. Edge Config (the previous URL source) was removed: it duplicated the
  // router snapshot and its per-store 3-config cap blocked new stores.
  deploymentUrl?: string | null
}

// Edge entrypoint. The function is declared as `middleware` here because that
// is the Next 15 convention. When the orchestrator ships this file to a Next
// 16+ store, `renderEdgeTemplate(PROXY_CONVENTION_PATH)` rewrites the
// declaration to `export async function proxy(` — Next 16 requires the entry
// function to be named `proxy` (or default), not just the file. This mirrors
// the official @next/codemod middleware-to-proxy, which renames both file and
// function together.
export async function proxy(req: NextRequest) {
  const pathname = req.nextUrl.pathname
  return applyRelayCacheControl(applyFrameAncestors(await route(req), pathname), pathname)
}

async function route(req: NextRequest) {
  // ── Draft password gate. Runs BEFORE A/B. Inert unless this deployment was
  // baked with DRAFT_PASSWORD_* (draft builds only) — so live + A/B variant
  // deployments skip it entirely and behave exactly as before. When active and
  // the visitor is not unlocked, it returns the branded page / handles unlock;
  // when unlocked it returns null and falls through to the normal path. ───────
  if (DRAFT_PASSWORD_ENABLED && DRAFT_PASSWORD_HASH && DRAFT_GATE_SECRET) {
    const gated = await draftPasswordGate(req)
    if (gated) return gated
    // Unlocked. On a top-level HTML navigation, re-fetch the page and inject the
    // DRAFT banner into it. Returns null for asset/data requests and for the
    // middleware's own inner fetch, so the normal path is untouched there.
    const withBanner = await injectDraftBanner(req)
    if (withBanner) return withBanner
  }

  // ── H1: short-circuit on flag-off stores. MUST be the first line. ──────────
  if (!AB_ENABLED || !ROUTER_URL || !ROUTER_SECRET || !STORE_ID) {
    // Diagnostic-friendly short-circuit: expose which env piece is missing so
    // the publish-time multi-theme env-var self-heal can be debugged from a
    // simple `curl -I`. No PII, no secrets — just yes/no flags for the
    // canonical env vars. Cheap (one boolean per env on flag-off stores).
    const response = NextResponse.next()
    response.headers.set(
      'x-amb-short-circuit',
      [
        AB_ENABLED ? 'AB_ENABLED' : '!AB_ENABLED',
        ROUTER_URL ? 'ROUTER_URL' : '!ROUTER_URL',
        ROUTER_SECRET ? 'ROUTER_SECRET' : '!ROUTER_SECRET',
        STORE_ID ? 'STORE_ID' : '!STORE_ID',
      ].join(','),
    )
    // Mint the per-visitor id even when theme A/B is OFF. `amb_vid` is the
    // sticky visitor key that the PRODUCT-page (PDP) A/B feature needs — that
    // feature is server-side in Medusa and runs independently of the theme
    // router, so its visitor cookie must not be gated behind the theme-A/B
    // flags above. The Medusa backend decides per request whether any PDP
    // experiment is actually running; the storefront's only job is to always
    // carry a stable visitor id. Strictly-necessary, no profiling (random UUID).
    if (!req.cookies.get('amb_vid')?.value) {
      response.cookies.set('amb_vid', crypto.randomUUID(), {
        ...COOKIE_OPTS,
        maxAge: THIRTY_DAYS,
      })
    }
    return applyGeoConsent(req, response)
  }

  // ── Bots: serve control deterministically. Strip ?_v so crawlers cannot
  //    fragment indexing by following a leaked preview URL (review item C3).
  const ua = req.headers.get('user-agent') ?? ''
  if (BOT_UA_RE.test(ua)) {
    if (req.nextUrl.searchParams.has('_v')) {
      const stripped = new URL(req.nextUrl.toString())
      stripped.searchParams.delete('_v')
      return NextResponse.redirect(stripped)
    }
    return NextResponse.next()
  }

  // ── Asset proxy branch ─────────────────────────────────────────────────────
  // Requests for /_next/static/chunks/* and /_next/static/css/* must be
  // routed to the SAME deploy that produced the HTML referencing them, or
  // the buyer gets cross-deploy chunk skew (different content hashes between
  // control and variant builds). The cookie tells us which deploy that is.
  //
  // No cookie ⇒ this is either a cold visit (HTML response will set the
  // cookie) or a control buyer ⇒ either way serve control assets. Bad
  // cookie ⇒ also serve control (defense in depth, no PII).
  const isAssetRequest = req.nextUrl.pathname.startsWith('/_next/static/')
  if (isAssetRequest) {
    const cookieRaw = req.cookies.get('amb_theme')?.value
    if (!cookieRaw) return NextResponse.next()
    const verified = await verifyCookie(cookieRaw, ROUTER_SECRET)
    if (!verified) return NextResponse.next()
    // The signed cookie carries the variant deploy URL (empty ⇒ control).
    // Trusted because the payload is HMAC-verified above. No router/Edge Config
    // call on the asset hot path.
    const variantUrl = verified.deploymentUrl
    if (!variantUrl) return NextResponse.next()
    try {
      const rewriteUrl = new URL(
        req.nextUrl.pathname + req.nextUrl.search,
        variantUrl,
      )
      return NextResponse.rewrite(rewriteUrl)
    } catch {
      return NextResponse.next()
    }
  }

  // ── ?_v=<slug> preview override (review item C3) ───────────────────────────
  // Requires either:
  //   1. an admin auth cookie set by the orchestrator dashboard, OR
  //   2. PREVIEW_OVERRIDE_ENABLED=true (staging escape hatch)
  // Without one of these the param is silently ignored — it never leaks
  // variants to anonymous traffic. Note: the cookie's existence is checked
  // but not cryptographically verified at this layer; the orchestrator
  // dashboard issues it short-TTL + scoped to the storefront origin.
  const previewSlug = req.nextUrl.searchParams.get('_v')
  if (previewSlug) {
    const isAdmin = !!req.cookies.get('amb_admin')?.value
    if (isAdmin || PREVIEW_OVERRIDE_ENABLED) {
      const resolved = await callRouter(req, ua, { previewSlug })
      if (resolved) {
        return finalize(req, resolved)
      }
      // Router error on explicit preview → fall through to normal flow
      // rather than 5xx the admin.
    }
  }

  // ── Cookie fast path ───────────────────────────────────────────────────────
  // Cookie payload is base64url(JSON({themeId, groupVersion})).base64url(hmac).
  // We do NOT trust a deploymentUrl from the cookie (review item C1).
  const cookieRaw = req.cookies.get('amb_theme')?.value
  if (cookieRaw) {
    const verified = await verifyCookie(cookieRaw, ROUTER_SECRET)
    if (verified) {
      // Fast path: within RESOLVE_TTL_MS AND while the device is unchanged, trust
      // the signed cookie and skip the router entirely — no cross-region
      // router+Redis round-trip on this page view. The assignment stays sticky
      // (correct for a running experiment). The HTML rewrite target is the
      // cookie's signed deploymentUrl (same value the asset branch already trusts).
      // The device check keeps device-targeted assignments live across a device
      // switch (e.g. responsive testing) — a changed device re-resolves below.
      const age =
        typeof verified.resolvedAt === 'number' ? Date.now() - verified.resolvedAt : Infinity
      const sameDevice = verified.device === classifyDevice(ua)
      if (age >= 0 && age < RESOLVE_TTL_MS && sameDevice) {
        return finalize(
          req,
          {
            themeId: verified.themeId,
            groupVersion: verified.groupVersion,
            abGroupId: verified.abGroupId ?? null,
            deploymentUrl: verified.deploymentUrl ?? '',
            isControl: !verified.deploymentUrl,
          },
          { skipThemeCookieWrite: true }, // preserve resolvedAt → honour the TTL window
        )
      }
      // TTL expired (or a pre-v4 cookie with no resolvedAt) → re-resolve through
      // the router to pick up any lifecycle / targeting / weight / rebuild change,
      // then refresh the cookie (resets resolvedAt, starting a new TTL window).
      const resolved = await callRouter(req, ua, {
        ambFp: req.cookies.get('amb_fp')?.value,
      })
      if (!resolved) return applyGeoConsent(req, NextResponse.next()) // router down → control
      return finalize(req, resolved)
    }
    // Cookie present but signature/structure invalid → treat as miss.
  }

  // ── Cookie miss: call FastAPI /v1/resolve ──────────────────────────────────
  const resolved = await callRouter(req, ua, {
    ambFp: req.cookies.get('amb_fp')?.value,
  })
  if (!resolved) return applyGeoConsent(req, NextResponse.next()) // router unreachable → serve control
  return finalize(req, resolved)
}

// ─── helpers ────────────────────────────────────────────────────────────────

interface CallRouterExtras {
  ambFp?: string
  previewSlug?: string
}

async function callRouter(
  req: NextRequest,
  ua: string,
  extras: CallRouterExtras,
): Promise<ResolveResponse | null> {
  try {
    const res = await fetch(`${ROUTER_URL}/v1/resolve`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-router-secret': ROUTER_SECRET ?? '',
      },
      body: JSON.stringify({
        storeId: STORE_ID,
        ip: req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? '',
        country: req.headers.get('x-vercel-ip-country') ?? '',
        region: req.headers.get('x-vercel-ip-country-region') ?? '',
        language: req.headers.get('accept-language') ?? '',
        timezone: req.headers.get('x-vercel-ip-timezone') ?? '',
        userAgent: ua,
        utmSource: req.nextUrl.searchParams.get('utm_source') ?? undefined,
        ambFp: extras.ambFp,
        ambVid: req.cookies.get('amb_vid')?.value,
        previewSlug: extras.previewSlug,
      }),
    })
    if (!res.ok) return null
    return (await res.json()) as ResolveResponse
  } catch {
    return null
  }
}

interface FinalizeOptions {
  /** When the router confirmed the same (themeId, groupVersion) as the
   *  cookie already carries, skip rewriting the amb_theme cookie.
   *  The cookie's max-age does not roll forward — that's intentional;
   *  the buyer's experience stays pinned to the original assignment
   *  until the snapshot rotates. */
  skipThemeCookieWrite?: boolean
}

async function finalize(
  req: NextRequest,
  resolved: ResolveResponse,
  opts: FinalizeOptions = {},
): Promise<NextResponse> {
  let response: NextResponse
  if (resolved.isControl) {
    response = NextResponse.next()
  } else {
    // Variant deploy URL comes straight from the router's resolve response.
    // The router snapshot is refreshed by the orchestrator on every A/B
    // lifecycle event (launch / weight / targeting / enable / promote /
    // cancel) from the same DB rows that used to feed Edge Config, so it is
    // the single source of truth for "where is the current variant served?".
    const variantUrl = resolved.deploymentUrl
    if (!variantUrl) {
      // No URL yet (snapshot mid-build / propagation lag) — fall back to
      // control. Buyer sees the same control HTML uncookied visitors see; no
      // broken state.
      response = NextResponse.next()
    } else {
      let rewriteUrl: URL
      try {
        rewriteUrl = new URL(
          req.nextUrl.pathname + req.nextUrl.search,
          variantUrl,
        )
      } catch {
        return applyGeoConsent(req, NextResponse.next())
      }
      response = NextResponse.rewrite(rewriteUrl)
    }
  }

  if (!opts.skipThemeCookieWrite && ROUTER_SECRET) {
    const signed = await signCookie(
      {
        themeId: resolved.themeId,
        groupVersion: resolved.groupVersion,
        abGroupId: resolved.abGroupId ?? null,
        // Stamp the resolve time so the HTML fast path can trust this cookie for
        // RESOLVE_TTL_MS before re-resolving. Always written on a fresh resolve,
        // which resets the TTL window.
        resolvedAt: Date.now(),
        // Stamp the device this assignment was resolved for; the fast path
        // re-resolves if the request's device later differs (keeps device
        // targeting live across a device switch).
        device: classifyDevice(req.headers.get('user-agent') || ''),
        // Persist the (signed) variant URL so the asset-proxy branch can
        // rewrite /_next/static/* without a router call. Empty for control.
        deploymentUrl: resolved.isControl ? '' : (resolved.deploymentUrl ?? ''),
      },
      ROUTER_SECRET,
    )
    response.cookies.set('amb_theme', signed, { ...COOKIE_OPTS, maxAge: THIRTY_DAYS })
  }
  if (resolved.fingerprint) {
    response.cookies.set('amb_fp', resolved.fingerprint, {
      ...COOKIE_OPTS,
      maxAge: NINETY_DAYS,
    })
  }
  if (!req.cookies.get('amb_vid')?.value) {
    response.cookies.set('amb_vid', crypto.randomUUID(), {
      ...COOKIE_OPTS,
      maxAge: THIRTY_DAYS,
    })
  }
  return applyGeoConsent(req, response)
}

// HMAC cookie sign/verify using Web Crypto (works at Vercel edge).
// Format: `<base64url(JSON)>.<base64url(hmac_sha256(secret, base64url(JSON)))>`

async function signCookie(payload: CookiePayload, secret: string): Promise<string> {
  const json = JSON.stringify(payload)
  const data = b64urlEncode(new TextEncoder().encode(json))
  const sig = await hmacSign(data, secret)
  return `${data}.${sig}`
}

async function verifyCookie(
  cookie: string,
  secret: string,
): Promise<CookiePayload | null> {
  const dot = cookie.indexOf('.')
  if (dot <= 0 || dot === cookie.length - 1) return null
  const data = cookie.slice(0, dot)
  const sig = cookie.slice(dot + 1)
  const expected = await hmacSign(data, secret)
  // Constant-time compare (review item C1 hardening).
  if (!timingSafeEqual(sig, expected)) return null
  let parsed: unknown
  try {
    parsed = JSON.parse(new TextDecoder().decode(b64urlDecode(data)))
  } catch {
    return null
  }
  if (
    !parsed ||
    typeof parsed !== 'object' ||
    typeof (parsed as CookiePayload).themeId !== 'string' ||
    typeof (parsed as CookiePayload).groupVersion !== 'string'
  ) {
    return null
  }
  return parsed as CookiePayload
}

async function hmacSign(data: string, secret: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    toBufferSource(new TextEncoder().encode(secret)),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  )
  const sigBuf = await crypto.subtle.sign('HMAC', key, toBufferSource(new TextEncoder().encode(data)))
  return b64urlEncode(new Uint8Array(sigBuf))
}

function b64urlEncode(bytes: Uint8Array): string {
  let bin = ''
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i])
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function b64urlDecode(s: string): Uint8Array {
  const pad = s.length % 4 === 0 ? '' : '='.repeat(4 - (s.length % 4))
  const b64 = s.replace(/-/g, '+').replace(/_/g, '/') + pad
  const bin = atob(b64)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return diff === 0
}

// ── Draft password gate (CONTRACT v7) ──────────────────────────────────────
// Returns a Response to serve (page / unlock redirect), or null when the
// visitor is already unlocked (caller falls through to normal handling).
async function draftPasswordGate(req: NextRequest): Promise<NextResponse | null> {
  const url = new URL(req.url)

  // Unlock submit: POST to the current path with ?__amboras_unlock=1 (avoids
  // any matcher change — the page path is already matched; middleware runs
  // before the route so the storefront never sees this POST).
  if (req.method === 'POST' && url.searchParams.has(DRAFT_UNLOCK_QUERY)) {
    let password = ''
    try {
      const form = await req.formData()
      password = String(form.get('password') || '')
    } catch { password = '' }
    const ok = await verifyDraftPassword(password, DRAFT_PASSWORD_HASH || '')
    if (!ok) return draftPasswordPage(true)
    const exp = Math.floor(Date.now() / 1000) + DRAFT_COOKIE_TTL_S
    const sig = await hmacSign(String(exp), DRAFT_GATE_SECRET || '')
    const dest = new URL(req.url)
    dest.searchParams.delete(DRAFT_UNLOCK_QUERY)
    const res = NextResponse.redirect(dest, 303)
    res.cookies.set(DRAFT_UNLOCK_COOKIE, exp + '.' + sig, {
      httpOnly: true,
      secure: true,
      sameSite: 'lax',
      path: '/',
      maxAge: DRAFT_COOKIE_TTL_S,
    })
    return res
  }

  // ADMIN skip-prompt: a short-lived signed token (?__amboras_admin=<exp>.<sig>)
  // minted server-side for the owner. Same signature as the unlock cookie, so
  // draftCookieValid validates it. On success set the normal 8h unlock cookie and
  // redirect to a CLEAN url so the token never lingers. It carries NO password.
  const adminToken = url.searchParams.get(DRAFT_ADMIN_QUERY)
  if (adminToken) {
    // Valid or not, the token NEVER stays in the URL: valid → unlock cookie +
    // clean redirect; expired/forged → clean redirect only (the gate then
    // prompts on the clean URL). Copy/paste of a stale admin link must not
    // carry the param around.
    const embedded = url.searchParams.get(DRAFT_EMBED_QUERY) === '1'
    const dest = new URL(req.url)
    dest.searchParams.delete(DRAFT_ADMIN_QUERY)
    dest.searchParams.delete(DRAFT_EMBED_QUERY)
    const res = NextResponse.redirect(dest, 303)
    if (await draftCookieValid(adminToken)) {
      const exp = Math.floor(Date.now() / 1000) + DRAFT_COOKIE_TTL_S
      const sig = await hmacSign(String(exp), DRAFT_GATE_SECRET || '')
      // Framed (admin pane): Lax is withheld on the framed navigation, and a
      // partitioned cookie stays scoped to the admin's top-level site.
      const frameSafe = embedded
        ? { sameSite: 'none' as const, partitioned: true }
        : { sameSite: 'lax' as const }
      res.cookies.set(DRAFT_UNLOCK_COOKIE, exp + '.' + sig, {
        httpOnly: true,
        secure: true,
        path: '/',
        maxAge: DRAFT_COOKIE_TTL_S,
        ...frameSafe,
      })
      if (embedded) {
        res.cookies.set(DRAFT_EMBED_COOKIE, '1', {
          httpOnly: true,
          secure: true,
          path: '/',
          maxAge: DRAFT_COOKIE_TTL_S,
          ...frameSafe,
        })
      }
    }
    return res
  }

  const cookie = req.cookies.get(DRAFT_UNLOCK_COOKIE)?.value
  if (cookie && (await draftCookieValid(cookie))) return null
  return draftPasswordPage(false)
}

async function draftCookieValid(raw: string): Promise<boolean> {
  const dot = raw.indexOf('.')
  if (dot <= 0) return false
  const expStr = raw.slice(0, dot)
  const sig = raw.slice(dot + 1)
  const exp = Number(expStr)
  if (!Number.isFinite(exp) || exp * 1000 <= Date.now()) return false
  const expected = await hmacSign(expStr, DRAFT_GATE_SECRET || '')
  return timingSafeEqual(sig, expected)
}

// Web-Crypto PBKDF2-SHA256 verify — must match the orchestrator's
// pbkdf2$iter$salt$hash (common/utils/draft-password.util.ts). Never throws.
async function verifyDraftPassword(password: string, stored: string): Promise<boolean> {
  if (!password || !stored) return false
  const parts = stored.split('$')
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false
  const iterations = Number(parts[1])
  if (!Number.isInteger(iterations) || iterations <= 0) return false
  const salt = hexToBytes(parts[2])
  const expected = hexToBytes(parts[3])
  if (salt.length === 0 || expected.length === 0) return false
  try {
    const key = await crypto.subtle.importKey(
      'raw',
      toBufferSource(new TextEncoder().encode(password)),
      'PBKDF2',
      false,
      ['deriveBits'],
    )
    const bits = await crypto.subtle.deriveBits(
      { name: 'PBKDF2', salt: toBufferSource(salt), iterations, hash: 'SHA-256' },
      key,
      expected.length * 8,
    )
    const actual = new Uint8Array(bits)
    if (actual.length !== expected.length) return false
    let diff = 0
    for (let i = 0; i < actual.length; i++) diff |= actual[i] ^ expected[i]
    return diff === 0
  } catch {
    return false
  }
}

function hexToBytes(hex: string): Uint8Array {
  if (hex.length % 2 !== 0 || /[^0-9a-f]/i.test(hex)) return new Uint8Array(0)
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16)
  return out
}

// Web Crypto's `BufferSource` requires an `ArrayBuffer` backing. Under
// TS 5.7+ `Uint8Array` is generic over its buffer and `TextEncoder().encode()`
// / hex-decoded arrays widen to `Uint8Array<ArrayBufferLike>` (which admits
// `SharedArrayBuffer`), so passing them straight to `crypto.subtle.*` fails the
// storefront build with TS2322. Copy into a fresh, definitely-`ArrayBuffer`
// view first. Returned as `BufferSource` — a lib.dom type present in every TS
// version, so this compiles on Next 15 and Next 16 storefronts alike.
function toBufferSource(u: Uint8Array): BufferSource {
  const copy = new Uint8Array(new ArrayBuffer(u.byteLength))
  copy.set(u)
  return copy
}

// Re-fetch the just-unlocked draft page and splice the DRAFT banner in before
// </body>. Runs only for top-level HTML GET navigations on a draft build; every
// other request (assets, data, the inner fetch itself, non-200/non-HTML) returns
// null so the caller falls through to the normal, untouched render. Buffered
// rather than streamed on purpose: draft traffic is tiny and a single string
// splice is far less error-prone than a chunk-boundary-aware stream transform.
async function injectDraftBanner(req: NextRequest): Promise<NextResponse | null> {
  if (req.headers.get(DRAFT_BANNER_INNER_HEADER)) return null // our own inner fetch — never recurse
  if (req.method !== 'GET') return null
  const accept = req.headers.get('accept') || ''
  if (!accept.includes('text/html')) return null
  const path = new URL(req.url).pathname
  if (path.startsWith('/_next/') || path.startsWith('/api/')) return null
  const framed = isFramedDraftNavigation(req)

  const innerHeaders = new Headers(req.headers)
  innerHeaders.set(DRAFT_BANNER_INNER_HEADER, '1')
  let origin: Response
  try {
    origin = await fetch(req.url, { headers: innerHeaders, redirect: 'manual' })
  } catch {
    return null // sub-fetch failed → serve the page bannerless rather than 500
  }
  const contentType = origin.headers.get('content-type') || ''
  if (origin.status !== 200 || !contentType.includes('text/html') || !origin.body) return null

  let html: string
  try {
    html = await origin.text()
  } catch {
    return null
  }
  const marker = '</body>'
  const at = html.lastIndexOf(marker)
  const banner = framed ? draftEmbedReadyMarkup() : draftBannerMarkup()
  const body = at === -1 ? html + banner : html.slice(0, at) + banner + html.slice(at)

  const headers = new Headers(origin.headers)
  headers.delete('content-length') // body length changed by the splice
  headers.delete('content-encoding') // fetch already decoded the body
  return new NextResponse(body, { status: origin.status, headers })
}

// Embed cookie is a fallback for browsers that send no Sec-Fetch-Dest.
function isFramedDraftNavigation(req: NextRequest): boolean {
  const dest = req.headers.get('sec-fetch-dest')
  if (dest) return dest === 'iframe'
  return req.cookies.get(DRAFT_EMBED_COOKIE)?.value === '1'
}

// Framed by the admin: no banner, only a ready beacon once the page has loaded.
function draftEmbedReadyMarkup(): string {
  return (
    '<script>(function(){try{if(window.parent===window)return;' +
    ADMIN_ORIGINS_JS +
    'function go(){if(!document.body||!document.body.innerText.trim()){return;}' +
    'for(var i=0;i<OK.length;i++){window.parent.postMessage({type:"amb-draft-ready"},OK[i]);}}' +
    'if(document.readyState==="complete"){go();}else{window.addEventListener("load",go);}' +
    '}catch(e){}})();</script>'
  )
}

// The banner markup + a self-contained copy-link script. Mirrors the
// @amboras/ds ThemeBanner pattern (packages/ds/src/patterns/theme-banner) —
// that React component cannot be imported into this injected edge middleware,
// so the styles are kept in sync by hand. Bottom-center, 16px above the
// viewport edge: Amboras mark (24px), draft name + DRAFT pill, and — ONLY when
// the admin opener hands it over — a second line with the middle-truncated
// password and a copy control; Share pushed to the right. All quotes inside
// are double so the emitted string literals stay single-quoted and escape-free.
function draftBannerMarkup(): string {
  const name = escapeHtml(DRAFT_NAME)
  const copyIcon =
    '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M7 7m0 2.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667z"></path><path d="M4.012 16.737a2.005 2.005 0 0 1 -1.012 -1.737v-10c0 -1.1 .9 -2 2 -2h10c.75 0 1.158 .385 1.5 1"></path></svg>'
  const checkIcon =
    '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#16a34a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12l5 5l10 -10"></path></svg>'
  return (
    '<div id="amb-draft-banner" role="region" aria-label="Draft link" ' +
    'style="position:fixed;left:50%;bottom:16px;transform:translateX(-50%);z-index:2147483647;box-sizing:border-box;' +
    'width:calc(100% - 32px);max-width:768px;display:flex;align-items:center;gap:16px;' +
    'padding:12px 16px;border-radius:12px;background:#1b1b1b;color:#fff;' +
    'box-shadow:0 8px 32px rgba(0,0,0,.35);' +
    'font-family:system-ui,-apple-system,BlinkMacSystemFont,sans-serif;font-size:16px;line-height:1.5;text-align:left;">' +
    // Amboras mark — 24×24, muted.
    '<span aria-hidden="true" style="flex:none;display:block;width:24px;height:24px;overflow:hidden;opacity:.6;">' +
    AMBORAS_LOGO_SVG +
    '</span>' +
    // Text column: name + DRAFT pill on the first line, password on the second.
    '<span style="flex:1 1 auto;min-width:0;display:flex;flex-direction:column;gap:4px;">' +
    '<span style="min-width:0;display:flex;align-items:center;gap:8px;">' +
    '<span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600;letter-spacing:-.01em;">' +
    name +
    '</span>' +
    '<span style="flex:none;display:inline-flex;align-items:center;height:20px;padding:0 6px;border-radius:5px;' +
    'background:#c8603a;color:#f6d9cc;font-size:11px;font-weight:400;line-height:1;text-transform:uppercase;letter-spacing:.05em;">DRAFT</span>' +
    '</span>' +
    // Password line — hidden by default. Only ever filled when the ADMIN opener
    // sends the plaintext over postMessage (see the handshake script below), so
    // it never appears for a shared/incognito viewer.
    '<span id="amb-draft-pw" style="display:none;min-width:0;align-items:center;gap:8px;color:rgba(255,255,255,.45);">' +
    '<span id="amb-draft-pw-val" style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"></span>' +
    '<button id="amb-draft-pw-copy" type="button" title="Copy password" aria-label="Copy password" ' +
    'style="flex:none;display:grid;place-items:center;width:24px;height:24px;cursor:pointer;padding:0;border:0;border-radius:6px;background:transparent;color:inherit;">' +
    '<span id="amb-draft-pw-copy-i" style="display:contents;">' + copyIcon + '</span>' +
    '<span id="amb-draft-pw-copy-ok" style="display:none;">' + checkIcon + '</span>' +
    '</button>' +
    '</span>' +
    '</span>' +
    // Share — white, 44px tall, 8px radius.
    '<button id="amb-draft-share" type="button" ' +
    'style="flex:none;display:inline-flex;align-items:center;justify-content:center;height:44px;padding:0 24px;cursor:pointer;' +
    'border:0;border-radius:8px;background:#fff;color:#1b1b1b;font:inherit;font-weight:500;line-height:1;">Share</button>' +
    '</div>' +
    draftShareModalMarkup(name) +
    '<script>(function(){var b=document.getElementById("amb-draft-share");if(!b)return;' +
    'b.addEventListener("mouseenter",function(){b.style.background="rgba(255,255,255,.9)";});' +
    'b.addEventListener("mouseleave",function(){b.style.background="#fff";});' +
    // Share opens the in-page share modal (below): a YouTube-style dialog with
    // a row of share targets and the link with a Copy control.
    'var ov=document.getElementById("amb-share-ov");var dlg=document.getElementById("amb-share-dlg");' +
    'var cl=document.getElementById("amb-share-close");var inp=document.getElementById("amb-share-url");' +
    'var cpb=document.getElementById("amb-share-copy");if(!ov||!dlg||!cl||!inp||!cpb)return;' +
    'var u=window.location.href;var t=document.title||' + JSON.stringify(name) + ';' +
    'var eu=encodeURIComponent(u);var et=encodeURIComponent(t);inp.value=u;' +
    'var L={wa:"https://wa.me/?text="+et+"%20"+eu,sms:"sms:?&body="+eu,' +
    'fb:"https://www.facebook.com/sharer/sharer.php?u="+eu,' +
    'x:"https://twitter.com/intent/tweet?url="+eu+"&text="+et,' +
    'mail:"mailto:?subject="+et+"&body="+eu};' +
    'Object.keys(L).forEach(function(k){var a=document.getElementById("amb-share-"+k);if(a){a.href=L[k];}});' +
    'var last=null;' +
    'function show(){last=document.activeElement;ov.style.display="flex";document.body.style.overflow="hidden";cl.focus();}' +
    'function hide(){ov.style.display="none";document.body.style.overflow="";if(last&&last.focus){last.focus();}}' +
    'b.addEventListener("click",show);cl.addEventListener("click",hide);' +
    'ov.addEventListener("click",function(e){if(e.target===ov){hide();}});' +
    'document.addEventListener("keydown",function(e){if(e.key==="Escape"&&ov.style.display!=="none"){hide();}});' +
    'inp.addEventListener("focus",function(){inp.select();});' +
    'function ok(){cpb.textContent="Copied";setTimeout(function(){cpb.textContent="Copy";},1500);}' +
    'function fb(){try{inp.focus();inp.select();document.execCommand("copy");ok();}catch(e){}}' +
    'cpb.addEventListener("click",function(){' +
    'if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(u).then(ok).catch(fb);}else{fb();}});' +
    '})();' +
    // Admin password handshake: the banner asks its opener (the admin tab that
    // opened it) for the password over postMessage, and shows it ONLY when the
    // reply comes from one of our admin origins. A shared/incognito viewer has
    // no admin opener, so nothing is ever revealed to them.
    '(function(){' +
    'var slot=document.getElementById("amb-draft-pw");' +
    'var val=document.getElementById("amb-draft-pw-val");' +
    'var cp=document.getElementById("amb-draft-pw-copy");' +
    'var ci=document.getElementById("amb-draft-pw-copy-i");' +
    'var ck=document.getElementById("amb-draft-pw-copy-ok");' +
    'if(!slot||!val)return;' +
    ADMIN_ORIGINS_JS +
    'var pw="";' +
    // Middle-truncate: keep 14 leading + 2 trailing characters, like the DS pattern.
    'function tm(v){return v.length<=17?v:v.slice(0,14)+"…"+v.slice(-2);}' +
    'window.addEventListener("message",function(e){' +
    'if(OK.indexOf(e.origin)===-1)return;' +
    'var d=e.data;' +
    'if(!d||d.type!=="amb-draft-password"||typeof d.password!=="string"||!d.password)return;' +
    'pw=d.password;val.textContent=tm(pw);val.title=pw;slot.style.display="flex";' +
    '});' +
    'if(cp){' +
    'cp.addEventListener("mouseenter",function(){cp.style.background="rgba(255,255,255,.1)";cp.style.color="rgba(255,255,255,.8)";});' +
    'cp.addEventListener("mouseleave",function(){cp.style.background="transparent";cp.style.color="inherit";});' +
    'cp.addEventListener("click",function(){if(!pw)return;' +
    'function ok(){cp.setAttribute("aria-label","Password copied");if(ci&&ck){ci.style.display="none";ck.style.display="contents";}' +
    'setTimeout(function(){cp.setAttribute("aria-label","Copy password");if(ci&&ck){ci.style.display="contents";ck.style.display="none";}},1500);}' +
    'if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(pw).then(ok).catch(function(){});}else{ok();}' +
    '});}' +
    'try{if(window.opener){window.opener.postMessage({type:"amb-draft-hello"},"*");}}catch(e){}' +
    '})();</script>'
  )
}

// The share modal the banner's Share button opens — a YouTube-style dialog:
// title + close, a row of circular share targets (WhatsApp, Messages,
// Facebook, X, Email — each a plain share-intent link, no SDKs), and the draft
// URL in a read-only field with a Copy control. Hidden until Share is clicked.
// Icon paths are the @tabler/icons set the DS uses, inlined so the injected
// edge file stays dependency-free.
function draftShareModalMarkup(name: string): string {
  const ico = (paths: string, stroke: string): string =>
    '<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="' + stroke + '" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + paths + '</svg>'
  const targets: Array<{ id: string; label: string; bg: string; border?: string; icon: string; external: boolean }> = [
    { id: 'wa', label: 'WhatsApp', bg: '#25d366', external: true,
      icon: ico('<path d="M3 21l1.65 -3.8a9 9 0 1 1 3.4 2.9l-5.05 .9"></path><path d="M9 10a.5 .5 0 0 0 1 0v-1a.5 .5 0 0 0 -1 0v1a5 5 0 0 0 5 5h1a.5 .5 0 0 0 0 -1h-1a.5 .5 0 0 0 0 1"></path>', '#fff') },
    { id: 'sms', label: 'Messages', bg: '#1a73e8', external: false,
      icon: ico('<path d="M8 9h8"></path><path d="M8 13h6"></path><path d="M18 4a3 3 0 0 1 3 3v8a3 3 0 0 1 -3 3h-5l-5 3v-3h-2a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3h12"></path>', '#fff') },
    { id: 'fb', label: 'Facebook', bg: '#3b5998', external: true,
      icon: ico('<path d="M7 10v4h3v7h4v-7h3l1 -4h-4v-2a1 1 0 0 1 1 -1h3v-4h-3a5 5 0 0 0 -5 5v2h-3"></path>', '#fff') },
    { id: 'x', label: 'X', bg: '#000', border: '#3f3f3f', external: true,
      icon: ico('<path d="M4 4l11.733 16h4.267l-11.733 -16l-4.267 0"></path><path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772"></path>', '#fff') },
    { id: 'mail', label: 'Email', bg: '#f1f1f1', external: false,
      icon: ico('<path d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10"></path><path d="M3 7l9 6l9 -6"></path>', '#0f0f0f') },
  ]
  const items = targets
    .map(
      (t) =>
        '<a id="amb-share-' + t.id + '" href="#" ' + (t.external ? 'target="_blank" rel="noopener noreferrer" ' : '') +
        'style="flex:none;display:flex;flex-direction:column;align-items:center;gap:8px;width:80px;text-decoration:none;color:#f1f1f1;font-size:13px;line-height:1.3;">' +
        '<span style="display:grid;place-items:center;width:60px;height:60px;border-radius:50%;background:' + t.bg + ';' +
        (t.border ? 'box-shadow:inset 0 0 0 1px ' + t.border + ';' : '') + '">' + t.icon + '</span>' +
        '<span>' + t.label + '</span></a>',
    )
    .join('')
  return (
    '<div id="amb-share-ov" style="display:none;position:fixed;inset:0;z-index:2147483647;align-items:center;justify-content:center;' +
    'background:rgba(0,0,0,.6);font-family:system-ui,-apple-system,BlinkMacSystemFont,sans-serif;">' +
    '<div id="amb-share-dlg" role="dialog" aria-modal="true" aria-labelledby="amb-share-title" ' +
    'style="box-sizing:border-box;width:min(480px,calc(100% - 32px));border-radius:12px;background:#212121;color:#f1f1f1;' +
    'box-shadow:0 16px 48px rgba(0,0,0,.5);padding:16px 24px 24px;">' +
    '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;">' +
    '<h2 id="amb-share-title" style="margin:0;font-size:20px;font-weight:500;line-height:1.4;">Share ' + name + '</h2>' +
    '<button id="amb-share-close" type="button" aria-label="Close" ' +
    'style="display:grid;place-items:center;width:40px;height:40px;margin-right:-10px;border:0;border-radius:50%;background:transparent;color:#f1f1f1;cursor:pointer;">' +
    '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 6l-12 12"></path><path d="M6 6l12 12"></path></svg>' +
    '</button></div>' +
    '<div style="display:flex;gap:8px;overflow-x:auto;padding:4px 0 12px;margin:0 -8px;scrollbar-width:none;">' +
    items +
    '</div>' +
    '<div style="display:flex;align-items:center;gap:8px;margin-top:12px;padding:8px 8px 8px 16px;border-radius:12px;border:1px solid #3f3f3f;background:#0f0f0f;">' +
    '<input id="amb-share-url" type="text" readonly aria-label="Draft link" ' +
    'style="flex:1 1 auto;min-width:0;border:0;outline:0;background:transparent;color:#f1f1f1;font:inherit;font-size:15px;">' +
    '<button id="amb-share-copy" type="button" ' +
    'style="flex:none;height:36px;padding:0 16px;border:0;border-radius:18px;background:#3ea6ff;color:#0f0f0f;font:inherit;font-size:14px;font-weight:500;cursor:pointer;">Copy</button>' +
    '</div>' +
    '</div></div>'
  )
}

function escapeHtml(s: string): string {
  return String(s).replace(/[&<>"']/g, function (c) {
    return c === '&'
      ? '&amp;'
      : c === '<'
        ? '&lt;'
        : c === '>'
          ? '&gt;'
          : c === '"'
            ? '&quot;'
            : '&#39;'
  })
}

function draftPasswordPage(error: boolean): NextResponse {
  // Visual system deliberately mirrors the DS-generated preview gate
  // (provisioning/preview-unavailable.generated.ts → the "You don't have
  // access" card) so both Amboras preview gates look identical. That module
  // lives in the orchestrator runtime and cannot be imported into this injected
  // edge middleware, so the .amb-preview-* styles are kept in sync by hand.
  const logo = AMBORAS_LOGO_SVG
  const err = error
    ? '<p class="amb-preview-error">Incorrect password. Try again.</p>'
    : ''
  const html =
    '<!DOCTYPE html><html lang="en" data-amboras-preview="password"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width, initial-scale=1">' +
    '<meta name="color-scheme" content="dark">' +
    '<meta name="robots" content="noindex, nofollow"><title>Password protected — Amboras</title>' +
    '<style>.amb-preview-page,.amb-preview-page *{box-sizing:border-box}' +
    '.amb-preview-page{display:grid;place-items:center;min-height:100vh;min-height:100svh;margin:0;padding:24px;background:#090a08;color:#fafafa;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;-webkit-font-smoothing:antialiased}' +
    '.amb-preview-card{width:100%;max-width:440px;padding:28px 30px 32px;background:#272825;border:1px solid #484944;border-radius:30px;box-shadow:0 16px 32px -20px #0008;text-align:left}' +
    '.amb-preview-logo{display:block;width:44px;height:46px;margin-bottom:24px}.amb-preview-logo svg{display:block;width:100%;height:100%}' +
    '.amb-preview-card h1{margin:0 0 12px;font-size:30px;line-height:1.2;font-weight:600;letter-spacing:-.025em;color:#fafafa}' +
    '.amb-preview-card p{margin:0;color:#a6a7a3;font-size:17px;line-height:1.55}' +
    '.amb-preview-form{margin-top:24px}.amb-preview-error{margin:0 0 12px;color:#e6a15f;font-size:15px;line-height:1.5}' +
    '.amb-preview-input{width:100%;min-height:44px;padding:9px 16px;border:1px solid #60615c;border-radius:10px;background:#1c1d1a;color:#fafafa;font-size:17px;margin-bottom:10px}' +
    '.amb-preview-input::placeholder{color:#7c7d78}.amb-preview-input:focus-visible{outline:2px solid #fafafa;outline-offset:2px;border-color:#898a84}' +
    '.amb-preview-submit{width:100%;min-height:44px;padding:8px 16px;border:1px solid #fff;border-radius:10px;color:#242522;background:linear-gradient(#fafafa,#e5e5e5);font-size:17px;font-weight:500;line-height:1.4;cursor:pointer;transition:background 140ms ease}' +
    '.amb-preview-submit:hover{background:#fff}.amb-preview-submit:focus-visible{outline:2px solid #fafafa;outline-offset:4px}' +
    '@media(max-width:520px){.amb-preview-card{padding:24px;border-radius:24px}.amb-preview-card h1{font-size:26px}}' +
    '@media(prefers-reduced-motion:reduce){.amb-preview-submit{transition:none}}</style></head>' +
    '<body><main class="amb-preview-page"><section class="amb-preview-card" aria-label="This is a dev store">' +
    '<div class="amb-preview-logo" role="img" aria-label="Amboras">' + logo + '</div>' +
    '<h1>This is a dev store</h1>' +
    '<p>This preview is password protected. Enter the password to continue.</p>' +
    '<form class="amb-preview-form" method="post" action="?' + DRAFT_UNLOCK_QUERY + '=1">' +
    err +
    '<input class="amb-preview-input" type="password" name="password" placeholder="Password" autofocus required>' +
    '<button class="amb-preview-submit" type="submit">View store</button>' +
    '</form></section></main>' +
    '<script>(function(){try{if(window.parent===window)return;' +
    ADMIN_ORIGINS_JS +
    'for(var i=0;i<OK.length;i++){window.parent.postMessage({type:"amb-draft-locked"},OK[i]);}' +
    '}catch(e){}})();</script>' +
    '</body></html>'
  return new NextResponse(html, {
    status: 401,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store',
      'x-robots-tag': 'noindex, nofollow',
    },
  })
}
