// AUTOGENERATED by amboras-dev-orchestrator (analytics v2).
// Do NOT edit by hand. Source of truth:
//   backend/src/modules/plugins/templates/analytics-template.ts
import { hasAnalyticsConsent } from '@/lib/cookie-consent'
import type { PostHog } from 'posthog-js'

const DEFAULT_HEARTBEAT_INTERVAL = 3000 // 3 seconds
const SLOW_HEARTBEAT_INTERVAL = 5000 // 5 seconds on slow connections
const FLUSH_INTERVAL = 3000 // 3 seconds
const MAX_BATCH_SIZE = 20
const SESSION_TIMEOUT = 30 * 60 * 1000 // 30 minutes

const SESSION_ID_KEY = 'amboras_session_id'
const LAST_ACTIVITY_KEY = 'amboras_last_activity'

// ── sessionStorage that cannot throw ────────────────────────────────────────
// Reading sessionStorage is not safe everywhere. iOS in-app webviews
// (Instagram, Facebook, TikTok), Safari Lockdown Mode and some private modes
// throw a SecurityError on ACCESS rather than returning null.
//
// getOrCreateSession() is the first thing the tracker does, so an unguarded
// throw there killed the whole session — no session_start, no page_view, no
// events at all. Silent, and concentrated in exactly the traffic a merchant
// gets when they run social campaigns: measured on August Berg, first-party
// Meta referrals fell 86% and mobile sessions 62% across the week their
// social spend ramped, while GA4 recorded that same channel going from zero
// to ~90 sessions/day.
//
// Every other storage access in this file was already wrapped; these were the
// three that were not.
//
// The fallback is an in-memory map. Session identity then lasts one page
// instead of one visit, so a multi-page visit reports as several sessions —
// worse stitching, but the visitor is measured instead of vanishing. The
// latch keeps reads and writes on the same store once either has failed;
// without it a working getItem paired with a throwing setItem (quota) would
// mint a fresh session id on every call.
const memoryStore = new Map<string, string>()
let storageUnavailable = false

function sessionGet(key: string): string | null {
  if (!storageUnavailable) {
    try {
      return sessionStorage.getItem(key)
    } catch {
      storageUnavailable = true
    }
  }
  return memoryStore.get(key) ?? null
}

function sessionSet(key: string, value: string): void {
  if (!storageUnavailable) {
    try {
      sessionStorage.setItem(key, value)
      return
    } catch {
      storageUnavailable = true
    }
  }
  memoryStore.set(key, value)
}

// crypto.randomUUID needs WebKit 15.4+; an older in-app webview throws a
// TypeError on the call — killing the session bootstrap exactly the way an
// unguarded sessionStorage did. Session ids only need to be unique per
// tenant-day for GROUP BY session_id, not cryptographically strong, so a
// Math.random fallback is fine for the stragglers.
function safeUuid(): string {
  try {
    return crypto.randomUUID()
  } catch {
    let out = ''
    for (let i = 0; i < 36; i++) {
      if (i === 8 || i === 13 || i === 18 || i === 23) out += '-'
      else if (i === 14) out += '4'
      // RFC 4122 variant nibble (8|9|a|b) — strict validators reject plain random.
      else if (i === 19) out += (8 + Math.floor(Math.random() * 4)).toString(16)
      else out += Math.floor(Math.random() * 16).toString(16)
    }
    return out
  }
}

// ── Multi-theme A/B attribution ─────────────────────────────────────────────
// The buyer's variant assignment is written by the edge middleware into the
// signed `amb_theme` cookie (payload: base64url(JSON).base64url(hmac)). The
// analytics beacon posts cross-origin, so that cookie never reaches the
// backend — we have to read it here and put the attribution INTO the event
// body. Ingestion reads top-level amb_vid/theme_id/ab_group_id per event and
// recognises a `theme_exposure` event type; without these fields the A/B
// rollup (which filters ab_group_id IS NOT NULL) excludes every event and the
// A/B testing page shows zeros.
//
// Signature is NOT verified here: it's verified at the edge, and a forged
// cookie at most mis-attributes the forger's own analytics — harmless.

const EXPOSURE_GUARD_KEY = 'amb_exposure_fired'
const PDP_CONTEXT_KEY = 'amb_pdp_ctx'

interface AbAttribution {
  amb_vid: string | null
  theme_id: string | null
  ab_group_id: string | null
}

// ── PDP A/B attribution is SESSION-scoped, not call-site-scoped ──────────────
// The PDP experiment assignment used to travel only in the `options` arg of
// trackPdpExposure/trackAddToCart, so it reached pdp_exposure events and
// nothing else — begin_checkout and purchase carried no variant, and the
// exposure→purchase funnel could only be rebuilt by joining on session_id.
// trackPdpExposure now latches the assignment here and buildPayload stamps it
// onto every subsequent event in the session (last-touch attribution), which
// survives the client-side navigation to /checkout.

interface PdpContext {
  experiment_id: string
  variant_id: string
}

// Routed through the sessionGet/sessionSet guard, not raw sessionStorage:
// in a storage-blocked webview the old swallow-and-degrade catch made this
// cohort emit pdp_exposure (ids ride inline on that event) but never attach
// PDP attribution to begin_checkout/purchase — exposures without attributable
// conversions, systematically understating the variant's conversion rate in
// the A/B z-test. The memory fallback keeps attribution for the page the
// exposure happened on, which is where most PDP-attributed conversions start.
function readPdpContext(): PdpContext | null {
  try {
    const raw = sessionGet(PDP_CONTEXT_KEY)
    if (!raw) return null
    const parsed = JSON.parse(raw)
    return typeof parsed?.experiment_id === 'string' &&
      typeof parsed?.variant_id === 'string'
      ? parsed
      : null
  } catch {
    // Malformed JSON → no PDP context. Per-event cookie attribution below is
    // unaffected. (Storage failure no longer lands here — the guard absorbs it.)
    return null
  }
}

function writePdpContext(ctx: PdpContext): void {
  sessionSet(PDP_CONTEXT_KEY, JSON.stringify(ctx))
}

function readPlainCookie(name: string): string | null {
  if (typeof document === 'undefined') return null
  const match = document.cookie
    .split('; ')
    .find((cookie) => cookie.startsWith(`${name}=`))
  if (!match) return null
  const value = match.slice(name.length + 1)
  return value ? decodeURIComponent(value) : null
}

function b64urlDecode(input: string): string {
  let s = input.replace(/-/g, '+').replace(/_/g, '/')
  const pad = s.length % 4
  if (pad) s += '='.repeat(4 - pad)
  return atob(s)
}

function readAbAttribution(): AbAttribution {
  const amb_vid = readPlainCookie('amb_vid')
  let theme_id: string | null = null
  let ab_group_id: string | null = null

  const cookie = readPlainCookie('amb_theme')
  if (cookie) {
    const dot = cookie.indexOf('.')
    const data = dot > 0 ? cookie.slice(0, dot) : cookie
    try {
      const payload = JSON.parse(b64urlDecode(data))
      if (payload && typeof payload === 'object') {
        theme_id = typeof payload.themeId === 'string' ? payload.themeId : null
        ab_group_id =
          typeof payload.abGroupId === 'string' ? payload.abGroupId : null
      }
    } catch {
      // malformed cookie → no attribution; events still send unstamped
    }
  }

  return { amb_vid, theme_id, ab_group_id }
}

// ── posthog-js richer-capture layer (additive) ──────────────────────────────
// Stock posthog-js in capture-only mode, pointed at OUR ingest pipeline
// (CloudFront → Lambda → Firehose → ClickHouse) — there is NO PostHog server.
// It adds the diagnostic layer the batching sender can't see: $autocapture
// clicks, $rageclick, $pageview/$pageleave (time-on-page + scroll depth) and
// $web_vitals — every event stamped with the same session/A-B super props, so
// each metric is segmentable per experiment variant in ClickHouse.
//
// The canonical events (session_start / page_view / heartbeat / session_end /
// commerce / exposures) KEEP flowing through the AnalyticsTracker below on
// whichever lane the store is on (legacy Medusa or v2 direct) — the posthog
// event set is disjoint ($-prefixed), so no duplicate ClickHouse rows.
//
// Everything server-dependent (feature flags / replay / surveys / remote
// assets) is disabled: the ingest Lambda only understands capture payloads.

let posthogClient: PostHog | null = null
let posthogLoading = false
// One console line max per page load: a dead capture layer must be
// diagnosable from the console. Expected skips (legacy lane, validator
// traffic) log at debug level; a bootstrap failure logs at warn.
let posthogBootNoted = false

function notePosthogDisabled(reason: string, err?: unknown): void {
  if (posthogBootNoted) return
  posthogBootNoted = true
  if (err === undefined) {
    console.debug('[amboras-analytics] posthog layer off: ' + reason)
  } else {
    console.warn('[amboras-analytics] posthog bootstrap failed: ' + reason, err)
  }
}

function ingestApiHost(): string | null {
  const url = process.env.NEXT_PUBLIC_ANALYTICS_INGEST_URL || ''
  if (!url) return null
  // The env var is the full capture URL (https://…/e/); posthog appends its
  // own /e/ path, so normalize down to the origin.
  return url.replace(/\/e\/?$/, '').replace(/\/+$/, '')
}

// Deploy-validation traffic must not pollute autocapture/A-B diagnostics.
function isSyntheticValidator(): boolean {
  if (
    typeof navigator !== 'undefined' &&
    navigator.userAgent.includes('AmborasValidator')
  ) {
    return true
  }
  return readPlainCookie('amb_vid') === 'amboras-validator-control'
}

// Super props are re-read from the cookies/session context on EVERY call, so
// re-registering (see refreshPosthogAttribution) is how posthog picks up
// attribution that only became available after init — the amb_vid cookie
// landing mid-session, or a PDP exposure being latched. Without a re-register
// the $-events keep shipping the stale props captured at init time.
function posthogSuperProps(sessionId: string | null): Record<string, string> {
  const attr = readAbAttribution()
  const pdp = readPdpContext()
  const props: Record<string, string> = {}
  if (sessionId) props.session_id = sessionId
  if (attr.amb_vid) props.amb_vid = attr.amb_vid
  if (attr.theme_id) props.theme_id = attr.theme_id
  if (attr.ab_group_id) props.ab_group_id = attr.ab_group_id
  if (pdp) {
    props.pdp_experiment_id = pdp.experiment_id
    props.pdp_variant_id = pdp.variant_id
    // Mirrored for the legacy COALESCE(pdp_variant_id, experiment_variant_id)
    // fallback in the Medusa pdp-ab results query.
    props.experiment_id = pdp.experiment_id
    props.experiment_variant_id = pdp.variant_id
  }
  return props
}

async function startPosthog(sessionId: string | null): Promise<void> {
  const apiHost = ingestApiHost()
  const key = process.env.NEXT_PUBLIC_ANALYTICS_KEY || ''
  if (!apiHost || !key) {
    // ingest not provisioned — canonical-only mode
    notePosthogDisabled('ingest env not provisioned (canonical-only mode)')
    return
  }
  if (isSyntheticValidator()) {
    notePosthogDisabled('synthetic validator traffic')
    return
  }
  if (posthogClient) {
    // Re-consent after a revoke: opt back in and refresh super props.
    posthogClient.opt_in_capturing()
    posthogClient.register(posthogSuperProps(sessionId))
    startCheckoutErrorObserver()
    return
  }
  if (posthogLoading) return
  posthogLoading = true
  try {
    // Bundle the web-vitals extension BEFORE init so posthog finds it locally —
    // remote asset loading is disabled below (first-party only, no CDN).
    // @ts-ignore — side-effect entrypoint ships without type declarations
    await import('posthog-js/dist/web-vitals')
    // Same first-party-only rationale for exception autocapture: bundle the
    // extension locally so $exception events (JS/checkout/render errors) land
    // without a remote CDN fetch (disable_external_dependency_loading below).
    // @ts-ignore — side-effect entrypoint ships without type declarations
    await import('posthog-js/dist/exception-autocapture')
    const { default: posthog } = await import('posthog-js')

    const attr = readAbAttribution()
    // Built as a loose record then cast: option names vary slightly across
    // posthog-js minors and unknown keys are ignored at runtime — a store's
    // Vercel build must never fail on a stricter config type.
    const config: Record<string, unknown> = {
      api_host: apiHost,
      // capture surface — the "richer" layer
      autocapture: true,
      rageclick: true,
      capture_pageview: false, // captured manually on route change (SPA)
      capture_pageleave: true,
      capture_performance: { web_vitals: true, network_timing: false },
      // $exception autocapture. OBJECT form merges over an ALL-FALSE base in
      // posthog-js (boolean true is what defaults the first two on) — every
      // key MUST stay explicit or unhandled-error capture silently turns off.
      capture_exceptions: {
        capture_unhandled_errors: true,
        capture_unhandled_rejections: true,
        // Checkout catch blocks console.error their failures (PayPal SDK,
        // cart.complete finalizer, route error boundary) — capture those too.
        capture_console_errors: true,
      },
      capture_dead_clicks: false,
      capture_heatmaps: false,
      // identity: amb_vid is the fleet-wide visitor id; no person profiles
      persistence: 'localStorage', // zero new cookies
      person_profiles: 'identified_only', // we never identify → anonymous only
      ...(attr.amb_vid ? { bootstrap: { distinctID: attr.amb_vid } } : {}),
      // kill every server-dependent subsystem (our Lambda is capture-only).
      // advanced_disable_flags replaced advanced_disable_decide (deprecated).
      advanced_disable_flags: true,
      advanced_disable_feature_flags: true,
      advanced_disable_feature_flags_on_first_load: true,
      disable_session_recording: true,
      disable_surveys: true,
      disable_external_dependency_loading: true,
      // transport
      ip: false, // geo derives from CloudFront headers server-side
      // hygiene: element chains on click-heavy pages can reach tens of KB
      sanitize_properties: (props: Record<string, unknown>) => {
        const chain = props.$elements_chain
        if (typeof chain === 'string' && chain.length > 4096) {
          props.$elements_chain = chain.slice(0, 4096)
        }
        return props
      },
    }
    const client = posthog.init(
      key,
      config as Parameters<typeof posthog.init>[1],
    )
    if (client) {
      client.register(posthogSuperProps(sessionId))
      posthogClient = client
      startCheckoutErrorObserver()
      // Consent may have been revoked while the module was loading.
      if (!hasAnalyticsConsent()) client.opt_out_capturing()
    }
  } catch (err) {
    // posthog failed to load (blocked, offline) — canonical analytics unaffected
    notePosthogDisabled('load/init threw', err)
    posthogClient = null
  } finally {
    posthogLoading = false
  }
}

// Re-stamp the posthog super props from the CURRENT cookies + PDP context.
// Called on session start, on every page view and on PDP exposure, so the
// $-event set carries the same attribution the canonical events get from
// buildPayload — including anything that landed after posthog.init().
function refreshPosthogAttribution(sessionId: string | null): void {
  posthogClient?.register(posthogSuperProps(sessionId))
}

function posthogPageView(): void {
  // posthog stamps $current_url/$pathname itself; this also rolls its scroll
  // manager so $pageleave carries per-page scroll depth + time-on-page.
  posthogClient?.capture('$pageview')
}

function stopPosthog(): void {
  // Persisted opt-out: no stray autocapture after consent is revoked. The
  // instance is kept so a re-consent can opt back in without a reload.
  posthogClient?.opt_out_capturing()
  stopCheckoutErrorObserver()
}

// ── Checkout error capture (posthog lane) ──────────────────────────────────
// Checkout failures are HANDLED errors — every catch block dead-ends in a
// toast or an inline alert, so $exception autocapture never sees them. This
// observer watches the two fixed error surfaces of the fleet checkout page
// and captures one 'checkout_error' per surfaced message. The event name is
// unknown to the canonical read layer (additive-safe); its props land in the
// ClickHouse properties JSON column, attribution comes free via super props.
// NOTE: this section deliberately avoids template literals and regexes so no
// escaping is needed inside ANALYTICS_TS_TEMPLATE.
const CHECKOUT_ERROR_DEDUP_MS = 5000
const CHECKOUT_ERROR_MAX_LEN = 500
// Sonner error toasts (portal near <body>) + the checkout page-level alert.
// Match on semantic attributes, NOT styling classes — 'text-destructive' also
// styles field-validation hints and would false-positive.
const CHECKOUT_TOAST_SELECTOR = '[data-sonner-toast][data-type="error"]'
const CHECKOUT_INLINE_SELECTOR = 'div[role="alert"][aria-live="assertive"]'

let checkoutErrorObserver: MutationObserver | null = null
const recentCheckoutErrors = new Map<string, number>()

function captureCheckoutError(
  message: string,
  source: 'toast' | 'inline' | 'manual',
  context?: Record<string, unknown>,
): void {
  if (!posthogClient || !hasAnalyticsConsent()) return
  const msg = (message || '').trim().slice(0, CHECKOUT_ERROR_MAX_LEN)
  if (!msg) return
  // Same message re-rendering within the window (toast stacking, React
  // strict double-effects) is one user-facing error, not several.
  const key = source + '|' + msg
  const now = Date.now()
  const last = recentCheckoutErrors.get(key)
  if (last !== undefined && now - last < CHECKOUT_ERROR_DEDUP_MS) return
  recentCheckoutErrors.set(key, now)
  if (recentCheckoutErrors.size > 20) {
    recentCheckoutErrors.forEach((t, k) => {
      if (now - t >= CHECKOUT_ERROR_DEDUP_MS) recentCheckoutErrors.delete(k)
    })
  }
  posthogClient.capture('checkout_error', {
    error_message: msg,
    error_source: source,
    pathname: window.location.pathname,
    ...context,
  })
}

function scanForCheckoutErrors(node: Node): void {
  if (!(node instanceof Element)) return
  if (node.matches(CHECKOUT_TOAST_SELECTOR)) {
    captureCheckoutError(node.textContent || '', 'toast')
  }
  node.querySelectorAll(CHECKOUT_TOAST_SELECTOR).forEach((el) => {
    captureCheckoutError(el.textContent || '', 'toast')
  })
  if (node.matches(CHECKOUT_INLINE_SELECTOR)) {
    captureCheckoutError(node.textContent || '', 'inline')
  }
  node.querySelectorAll(CHECKOUT_INLINE_SELECTOR).forEach((el) => {
    captureCheckoutError(el.textContent || '', 'inline')
  })
}

function startCheckoutErrorObserver(): void {
  if (checkoutErrorObserver) return
  if (typeof MutationObserver === 'undefined' || !document.body) return
  checkoutErrorObserver = new MutationObserver((mutations) => {
    // Body-wide observer (the sonner portal lives outside the page subtree);
    // this pathname gate keeps every other page a single-compare no-op.
    if (!window.location.pathname.startsWith('/checkout')) return
    for (const m of mutations) {
      m.addedNodes.forEach(scanForCheckoutErrors)
      // React swaps the text node when a MOUNTED alert shows a new message
      // (error -> clearError -> new error can reuse the same element).
      if (m.type === 'characterData') {
        const host = m.target.parentElement?.closest(
          CHECKOUT_TOAST_SELECTOR + ', ' + CHECKOUT_INLINE_SELECTOR,
        )
        if (host) {
          captureCheckoutError(
            host.textContent || '',
            host.hasAttribute('data-sonner-toast') ? 'toast' : 'inline',
          )
        }
      }
    }
  })
  checkoutErrorObserver.observe(document.body, {
    childList: true,
    subtree: true,
    characterData: true,
  })
}

function stopCheckoutErrorObserver(): void {
  checkoutErrorObserver?.disconnect()
  checkoutErrorObserver = null
}

interface AnalyticsEventContent {
  id: string
  quantity?: number
  item_price?: number
}

interface AnalyticsEvent {
  type: 'session_start' | 'page_view' | 'heartbeat' | 'session_end'
    | 'add_to_cart' | 'begin_checkout' | 'purchase' | 'theme_exposure' | 'pdp_exposure'
  url?: string
  referrer?: string
  title?: string
  utm_source?: string
  utm_medium?: string
  utm_campaign?: string
  utm_content?: string
  utm_term?: string
  product_id?: string
  variant_id?: string
  quantity?: number
  value?: number
  currency?: string
  order_id?: string
  item_count?: number
  cart_id?: string
  event_id?: string
  content_ids?: string[]
  contents?: AnalyticsEventContent[]
  experiment_id?: string
  experiment_variant_id?: string
  pdp_experiment_id?: string
  pdp_variant_id?: string
  // Multi-theme A/B attribution, stamped on flush from the amb_theme/amb_vid
  // cookies. Null/absent on stores not running an A/B test.
  amb_vid?: string | null
  theme_id?: string | null
  ab_group_id?: string | null
  // Heartbeat events only: the interval this tracker heartbeats at (3000
  // default, 5000 on slow-2g/2g). The read side derives dwell as
  // interval x heartbeat-count; without this it assumed a flat 3s and
  // under-counted slow connections by 40%.
  hb_ms?: number
  timestamp: number
}

interface AnalyticsPayload {
  store_id: string
  session_id: string
  events: AnalyticsEvent[]
}

function scheduleIdle(fn: () => void): void {
  if (typeof window !== 'undefined' && 'requestIdleCallback' in window) {
    window.requestIdleCallback(fn, { timeout: 2000 })
  } else {
    setTimeout(fn, 0)
  }
}

function getHeartbeatInterval(): number {
  if (typeof navigator !== 'undefined' && 'connection' in navigator) {
    const conn = navigator.connection
    if (conn?.effectiveType === 'slow-2g' || conn?.effectiveType === '2g') {
      return SLOW_HEARTBEAT_INTERVAL
    }
  }
  return DEFAULT_HEARTBEAT_INTERVAL
}

class AnalyticsTracker {
  private sessionId: string | null = null
  private storeId: string
  private publishableKey: string
  private endpoint: string
  private ingestUrl: string
  private ingestKey: string
  private eventQueue: AnalyticsEvent[] = []
  private heartbeatTimer: ReturnType<typeof setInterval> | null = null
  private flushTimer: ReturnType<typeof setInterval> | null = null
  private isInitialized = false
  private sessionEnded = false

  private handleVisibilityChange: () => void
  private handlePageHide: () => void

  constructor() {
    this.storeId = process.env.NEXT_PUBLIC_STORE_ID || ''
    this.publishableKey = process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY || ''
    const medusaUrl = process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL || ''
    this.endpoint = medusaUrl
      ? `${medusaUrl}/store/analytics`
      : process.env.NEXT_PUBLIC_ANALYTICS_ENDPOINT || ''
    this.ingestUrl = process.env.NEXT_PUBLIC_ANALYTICS_INGEST_URL || ''
    this.ingestKey = process.env.NEXT_PUBLIC_ANALYTICS_KEY || ''

    this.handleVisibilityChange = () => {
      if (document.visibilityState === 'hidden') {
        // Fire session_end at most once per session. visibilitychange (every
        // tab-away) and pagehide (unload) both land here / in handlePageHide,
        // and on mobile both fire together — without this guard a single visit
        // emits many session_end rows (they carry different timestamps, so the
        // ingest event_id dedup can't collapse them). Reset in startNewSession.
        if (!this.sessionEnded) {
          this.sessionEnded = true
          this.pushEvent({ type: 'session_end', url: window.location.pathname, timestamp: Date.now() })
        }
        this.flushBeacon()
        this.stopHeartbeat()
      } else {
        if (this.isSessionExpired()) {
          this.startNewSession()
        } else {
          this.startHeartbeat()
        }
      }
    }

    this.handlePageHide = () => {
      if (!this.sessionEnded) {
        this.sessionEnded = true
        this.pushEvent({ type: 'session_end', url: window.location.pathname, timestamp: Date.now() })
      }
      this.flushBeacon()
    }
  }

  private isV2(): boolean {
    return Boolean(this.ingestUrl && this.ingestKey)
  }

  init(): void {
    if (this.isInitialized) return
    if (!this.storeId) return
    if (!this.isV2() && (!this.endpoint || !this.publishableKey)) return
    if (!hasAnalyticsConsent()) return

    this.isInitialized = true
    this.startNewSession()
    void startPosthog(this.sessionId)

    document.addEventListener('visibilitychange', this.handleVisibilityChange)
    window.addEventListener('pagehide', this.handlePageHide)
  }

  private startNewSession(): void {
    this.sessionId = this.getOrCreateSession()
    this.sessionEnded = false
    refreshPosthogAttribution(this.sessionId)

    const utm = this.getUTMParams()
    this.pushEvent({
      type: 'session_start',
      url: window.location.pathname,
      referrer: document.referrer || undefined,
      title: document.title || undefined,
      ...utm,
      timestamp: Date.now(),
    })

    // Fire immediate heartbeat so user shows as "live" right away, then flush it.
    // hb_ms carries the interval this tracker heartbeats at (3s default, 5s on
    // slow-2g/2g) so the read side can derive dwell as interval x count —
    // a flat 3s multiplier under-counted slow connections by 40% and silently
    // raised their engaged-session bar to ~17s.
    this.pushEvent({ type: 'heartbeat', url: window.location.pathname, timestamp: Date.now(), hb_ms: getHeartbeatInterval() })
    this.flush()
    this.startHeartbeat()
    this.startFlushTimer()
  }

  trackPageView(url: string, title?: string): void {
    if (!this.isInitialized) return

    scheduleIdle(() => {
      this.pushEvent({
        type: 'page_view',
        url,
        title,
        timestamp: Date.now(),
      })
      // Re-read cookies + PDP context before capturing: the amb_vid cookie is
      // written by the edge middleware and can land after posthog.init(), so
      // the props registered at init are not necessarily complete.
      refreshPosthogAttribution(this.sessionId)
      posthogPageView()
      this.updateLastActivity()
    })
  }

  trackAddToCart(
    productId: string,
    variantId: string,
    quantity: number,
    value?: number,
    options?: {
      currency?: string
      experimentId?: string | null
      experimentVariantId?: string | null
      pdpExperimentId?: string | null
      pdpVariantId?: string | null
    },
  ): void {
    if (!this.isInitialized) return
    // Experiment ids are NOT read from `options` here any more — the envelope in
    // buildPayload stamps them from the session's latched PDP context, which is
    // what makes add_to_cart / begin_checkout / purchase all carry the variant.
    // The options fields are still accepted (the fleet's callers pass them) and
    // are honoured as an explicit override when the envelope has no context.
    const explicitExperiment = options?.pdpExperimentId || options?.experimentId
    const explicitVariant = options?.pdpVariantId || options?.experimentVariantId
    if (explicitExperiment && explicitVariant) {
      writePdpContext({
        experiment_id: explicitExperiment,
        variant_id: explicitVariant,
      })
    }
    this.pushEvent({
      type: 'add_to_cart',
      url: window.location.pathname,
      product_id: productId,
      variant_id: variantId,
      quantity,
      value,
      // `value` without `currency` is unitless — begin_checkout and purchase
      // have always carried it; add_to_cart never did.
      currency: options?.currency,
      timestamp: Date.now(),
    })
    this.updateLastActivity()
  }

  trackPdpExposure(
    productId: string,
    options: {
      experimentId: string
      experimentVariantId: string
      pdpExperimentId?: string
      pdpVariantId?: string
    },
  ): void {
    if (!this.isInitialized) return
    // Latch the assignment for the rest of the session: every later event
    // (add_to_cart, begin_checkout, purchase) picks it up from the envelope, and
    // the posthog $-events pick it up from the refreshed super props.
    writePdpContext({
      experiment_id: options.pdpExperimentId || options.experimentId,
      variant_id: options.pdpVariantId || options.experimentVariantId,
    })
    refreshPosthogAttribution(this.sessionId)
    this.pushEvent({
      type: 'pdp_exposure',
      url: window.location.pathname,
      product_id: productId,
      timestamp: Date.now(),
    })
    this.updateLastActivity()
  }

  trackBeginCheckout(
    cartId: string,
    value?: number,
    currency?: string,
    options?: {
      eventId?: string | null
      itemCount?: number
      contentIds?: string[]
      contents?: AnalyticsEventContent[]
    },
  ): void {
    if (!this.isInitialized) return
    // The /checkout mount effect re-runs on every refresh, back-navigation
    // and payment-error retry. Each re-fire used to land as a DISTINCT row,
    // because the deterministic event id hashes Date.now(). The stable
    // 'bc:<cart>:<session>' id below is what fixes that: re-sends collapse
    // under uniqExact(event_id) on read. Deliberately NOT also guarded in
    // localStorage — flush() is fire-and-forget with no retry, so a guard set
    // after a failed send would suppress the event permanently, trading a
    // harmless duplicate for a lost one.
    this.pushEvent({
      type: 'begin_checkout',
      url: '/checkout',
      cart_id: cartId,
      value,
      currency,
      item_count: options?.itemCount,
      event_id: options?.eventId || 'bc:' + cartId + ':' + this.sessionId,
      content_ids: options?.contentIds,
      contents: options?.contents,
      timestamp: Date.now(),
    })
    this.updateLastActivity()
  }

  trackPurchase(
    orderId: string,
    options?: {
      eventId?: string | null
      value?: number
      currency?: string
      itemCount?: number
      contentIds?: string[]
      contents?: AnalyticsEventContent[]
    },
  ): void {
    if (!this.isInitialized) return
    // The success page fires on render, so a refresh, a second tab, or a
    // shared /checkout/success?order= link re-emits. The stable 'pur:<orderId>'
    // id makes those re-emits idempotent on read: uniqExact(event_id) and the
    // funnel's order_id collapse both fold them into one purchase.
    //
    // No client-side "already fired" flag on purpose. flush() is
    // fire-and-forget (.catch(() => {}), no retry), so a flag written after a
    // send that silently failed — offline, adblock, 5xx — would suppress the
    // money event forever, and the refresh that recovers it today would stop
    // working. A duplicate row is free to fix on read; a missing purchase is
    // not. (Raw event feeds may show the repeat; every counting path dedups.)
    this.pushEvent({
      type: 'purchase',
      url: window.location.pathname,
      order_id: orderId,
      event_id: options?.eventId || 'pur:' + orderId,
      value: options?.value,
      currency: options?.currency,
      item_count: options?.itemCount,
      content_ids: options?.contentIds,
      contents: options?.contents,
      timestamp: Date.now(),
    })
    this.flush()
    this.updateLastActivity()
  }

  private pushEvent(event: AnalyticsEvent): void {
    this.eventQueue.push(event)
    if (this.eventQueue.length >= MAX_BATCH_SIZE) {
      this.flush()
    }
  }

  /**
   * Drain the queue into a payload, stamping A/B attribution onto every event
   * and piggybacking one `theme_exposure` per session when a group is active.
   * Returns null when there's nothing to send.
   */
  private buildPayload(): AnalyticsPayload | null {
    if (this.eventQueue.length === 0 || !this.sessionId) return null

    const events = [...this.eventQueue]
    this.eventQueue = []

    const attr = readAbAttribution()
    const pdp = readPdpContext()

    if (attr.ab_group_id) {
      // Fire one theme_exposure per session per group. Ingestion also dedups,
      // but this keeps batches small. Keyed by group id so a new experiment
      // re-fires exactly once. Pushed BEFORE the envelope below so it gets the
      // same attribution block as every other event.
      // sessionGet/sessionSet, not raw sessionStorage: in a storage-blocked
      // webview the amb_theme COOKIE still works, so this cohort's events all
      // carry ab_group_id — but the old catch skipped the exposure event the
      // per-theme metrics roll up from. Sessions attributed to a theme with
      // no exposure ever recorded skews the A/B denominators. No try/catch:
      // the guard swallows storage failures internally, so nothing here can
      // throw any more.
      if (sessionGet(EXPOSURE_GUARD_KEY) !== attr.ab_group_id) {
        events.push({
          type: 'theme_exposure',
          url: window.location.pathname,
          timestamp: Date.now(),
        })
        sessionSet(EXPOSURE_GUARD_KEY, attr.ab_group_id)
      }
    }

    // ── The attribution envelope ──────────────────────────────────────────────
    // Every session-scoped dimension is stamped on EVERY event, here, in one
    // place. Call sites supply domain data only (product_id, value, order_id…);
    // they never stamp attribution. This is what makes the payloads consistent
    // across event types — a heartbeat and a purchase in the same session now
    // carry an identical attribution block.
    //
    // Each field is stamped independently. They used to be nested: amb_vid was
    // hoisted out of the `ab_group_id` gate (visitor id is not an A/B concept),
    // but theme_id was left inside it, so a store with a theme assignment and no
    // running experiment shipped NO theme_id at all — 0 rows fleet-wide had
    // theme_id without ab_group_id. Do not re-nest these.
    for (const event of events) {
      if (attr.amb_vid && event.amb_vid == null) {
        event.amb_vid = attr.amb_vid
      }
      if (attr.theme_id && event.theme_id == null) {
        event.theme_id = attr.theme_id
      }
      if (attr.ab_group_id && event.ab_group_id == null) {
        event.ab_group_id = attr.ab_group_id
      }
      if (pdp) {
        if (event.pdp_experiment_id == null) {
          event.pdp_experiment_id = pdp.experiment_id
        }
        if (event.pdp_variant_id == null) {
          event.pdp_variant_id = pdp.variant_id
        }
        // Mirrored for the legacy COALESCE(pdp_variant_id,
        // experiment_variant_id) fallback in the Medusa pdp-ab results query.
        if (event.experiment_id == null) {
          event.experiment_id = pdp.experiment_id
        }
        if (event.experiment_variant_id == null) {
          event.experiment_variant_id = pdp.variant_id
        }
      }
    }

    return {
      store_id: this.storeId,
      session_id: this.sessionId,
      events,
    }
  }

  /**
   * v2 transport. `text/plain` keeps the cross-origin POST a CORS simple
   * request (no preflight) and lets sendBeacon carry it on unload; the ingest
   * Lambda parses the body as JSON regardless of content type. The publishable
   * key rides in the body because neither transport can set custom headers
   * without losing those properties.
   */
  private sendV2(payload: AnalyticsPayload, useBeacon: boolean): void {
    const body = JSON.stringify({ key: this.ingestKey, ...payload })
    if (useBeacon && typeof navigator !== 'undefined' && 'sendBeacon' in navigator) {
      try {
        const blob = new Blob([body], { type: 'text/plain' })
        if (navigator.sendBeacon(this.ingestUrl, blob)) return
      } catch {
        // fall through to fetch
      }
    }
    fetch(this.ingestUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain' },
      body,
      keepalive: true,
    }).catch(() => {
      // Silently fail — analytics should never break the store
    })
  }

  private flush(): void {
    const payload = this.buildPayload()
    if (!payload) return

    if (this.isV2()) {
      this.sendV2(payload, false)
      return
    }

    fetch(`${this.endpoint}/events`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Store-Environment-ID': this.storeId,
        'x-publishable-api-key': this.publishableKey,
      },
      body: JSON.stringify(payload),
      keepalive: true,
    }).catch(() => {
      // Silently fail — analytics should never break the store
    })
  }

  private flushBeacon(): void {
    const payload = this.buildPayload()
    if (!payload) return

    if (this.isV2()) {
      this.sendV2(payload, true)
      return
    }

    // sendBeacon doesn't support custom headers, so use fetch with keepalive
    fetch(`${this.endpoint}/events`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Store-Environment-ID': this.storeId,
        'x-publishable-api-key': this.publishableKey,
      },
      body: JSON.stringify(payload),
      keepalive: true,
    }).catch(() => {
      // Last resort: sendBeacon. It cannot carry X-Store-Environment-ID or
      // x-publishable-api-key, so Medusa may fail to route the batch —
      // accepted: this only fires when the keepalive fetch already failed
      // during unload, and losing a tail batch beats losing all of them.
      const blob = new Blob([JSON.stringify(payload)], { type: 'application/json' })
      navigator.sendBeacon(`${this.endpoint}/events`, blob)
    })
  }

  private startHeartbeat(): void {
    this.stopHeartbeat()
    const interval = getHeartbeatInterval()
    this.heartbeatTimer = setInterval(() => {
      if (document.visibilityState === 'visible') {
        scheduleIdle(() => {
          this.pushEvent({
            type: 'heartbeat',
            url: window.location.pathname,
            timestamp: Date.now(),
            // Interval this tracker heartbeats at — see the immediate
            // heartbeat in init() for why the read side needs it.
            hb_ms: interval,
          })
          this.updateLastActivity()
        })
      }
    }, interval)
  }

  private stopHeartbeat(): void {
    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer)
      this.heartbeatTimer = null
    }
  }

  private startFlushTimer(): void {
    this.stopFlushTimer()
    this.flushTimer = setInterval(() => {
      this.flush()
    }, FLUSH_INTERVAL)
  }

  private stopFlushTimer(): void {
    if (this.flushTimer) {
      clearInterval(this.flushTimer)
      this.flushTimer = null
    }
  }

  private getOrCreateSession(): string {
    const existingId = sessionGet(SESSION_ID_KEY)
    const lastActivity = sessionGet(LAST_ACTIVITY_KEY)

    if (existingId && lastActivity && !this.isSessionExpired()) {
      return existingId
    }

    const newId = safeUuid()
    sessionSet(SESSION_ID_KEY, newId)
    this.updateLastActivity()
    return newId
  }

  private isSessionExpired(): boolean {
    const lastActivity = sessionGet(LAST_ACTIVITY_KEY)
    if (!lastActivity) return true
    return Date.now() - parseInt(lastActivity, 10) > SESSION_TIMEOUT
  }

  private updateLastActivity(): void {
    sessionSet(LAST_ACTIVITY_KEY, Date.now().toString())
  }

  private getUTMParams(): {
    utm_source?: string
    utm_medium?: string
    utm_campaign?: string
    utm_content?: string
    utm_term?: string
  } {
    const params = new URLSearchParams(window.location.search)
    const result: {
      utm_source?: string
      utm_medium?: string
      utm_campaign?: string
      utm_content?: string
      utm_term?: string
    } = {}

    const source = params.get('utm_source')
    const medium = params.get('utm_medium')
    const campaign = params.get('utm_campaign')
    const content = params.get('utm_content')
    const term = params.get('utm_term')

    if (source) result.utm_source = source
    if (medium) result.utm_medium = medium
    if (campaign) result.utm_campaign = campaign
    if (content) result.utm_content = content
    if (term) result.utm_term = term

    return result
  }

  destroy(): void {
    this.stopHeartbeat()
    this.stopFlushTimer()
    this.flushBeacon()
    stopPosthog()
    document.removeEventListener('visibilitychange', this.handleVisibilityChange)
    window.removeEventListener('pagehide', this.handlePageHide)
    this.isInitialized = false
  }
}

let tracker: AnalyticsTracker | null = null

export function initAnalytics(): void {
  if (typeof window === 'undefined') return
  if (!tracker) tracker = new AnalyticsTracker()
  tracker.init()
}

export function trackPageView(url: string, title?: string): void {
  tracker?.trackPageView(url, title)
}

export function trackAddToCart(
  productId: string,
  variantId: string,
  quantity: number,
  value?: number,
  options?: {
    currency?: string
    experimentId?: string | null
    experimentVariantId?: string | null
    pdpExperimentId?: string | null
    pdpVariantId?: string | null
  },
): void {
  tracker?.trackAddToCart(productId, variantId, quantity, value, options)
}

export function trackPdpExposure(
  productId: string,
  options: {
    experimentId: string
    experimentVariantId: string
    pdpExperimentId?: string
    pdpVariantId?: string
  },
): void {
  tracker?.trackPdpExposure(productId, options)
}

export function trackBeginCheckout(
  cartId: string,
  value?: number,
  currency?: string,
  options?: {
    eventId?: string | null
    itemCount?: number
    contentIds?: string[]
    contents?: AnalyticsEventContent[]
  },
): void {
  tracker?.trackBeginCheckout(cartId, value, currency, options)
}

export function trackPurchase(
  orderId: string,
  options?: {
    eventId?: string | null
    value?: number
    currency?: string
    itemCount?: number
    contentIds?: string[]
    contents?: AnalyticsEventContent[]
  },
): void {
  tracker?.trackPurchase(orderId, options)
}

// Manual checkout-error capture for starter components that want clean
// semantics (provider, step, decline code) beyond the automatic UI observer.
// Safe to call anywhere: no-ops without posthog/consent.
export function trackCheckoutError(
  message: string,
  context?: Record<string, unknown>,
): void {
  captureCheckoutError(message, 'manual', context)
}

export function destroyAnalytics(): void {
  tracker?.destroy()
  tracker = null
}
